name: Deploy QA SerfitUP - Backend

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy en servidor QA
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 172.17.13.51
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "🔄 Actualizando backend"
            cd /var/www/qa-app/backend
            git fetch origin
            git reset --hard origin/qa

            echo "🔄 Actualizando frontend"
            cd /var/www/qa-app/frontend
            git fetch origin
            git reset --hard origin/qa

            echo "🐳 Rebuild Docker SIN CACHE"
            docker compose down
            docker compose build --no-cache
            docker compose up -d

            echo "✅ Deploy completado"
